# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ developer ]
  pull_request:
    branches: [ developer ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Dependencies
        run: .github/workflows/dependencies-ubuntu.sh

      - name: Versions
        run: |
            gcc --version
            mpicc --version
            h5pcc --version
            python3 --version
            make --version

      - name: Build
        run: |
            make sw4     CXX=h5pcc FC=gfortran debug=no hdf5=yes zfp=no prec=double -j2
            make sw4mopt CXX=h5pcc FC=gfortran debug=no hdf5=yes zfp=no prec=double -j2


