name: linux 

on:
  push:
    branches: [ developer ]
  pull_request:
    branches: [ developer ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: .github/workflows/dependencies-linux.sh

      - name: lib location
        run: |
            echo "fftw"
            ls -lh /usr/lib/x86_64-linux-gnu/fftw*
      #       echo "fftw lib"
      #       ls -lh /usr/lib/x86_64-linux-gnu/lib
      #       ls -lh /usr/lib/x86_64-linux-gnu/hdf5/openmpi
      #       ls -lh /usr/lib/x86_64-linux-gnu/hdf5/openmpi/include
      #       ls -lh /usr/lib/x86_64-linux-gnu/hdf5/openmpi/lib

      - name: Build
        run: |
            make sw4     CXX=mpicxx FC=gfortran debug=no hdf5=yes fftw=yes zfp=no prec=double EXTRA_LINK_FLAGS="-lgfortran -lhdf5 -llapack" HDF5ROOT=/usr/lib/x86_64-linux-gnu/hdf5/openmpi FFTWHOME=/usr/lib/x86_64-linux-gnu -j2

      - name: Test SW4
        working-directory: ./pytest
        run: ./test_sw4.py -m 2 -t 2 -v

      # - name: Test SW4mopt
      #   working-directory: ./pytest-sw4mopt
      #   run: python3 test_sw4mopt.py -d optimize_mp -v


