name: linux 

on:
  push:
    branches: [ developer ]
  pull_request:
    branches: [ developer ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: .github/workflows/dependencies-linux.sh

      - name: Build
        run: |
            make sw4     CXX=mpicxx FC=gfortran debug=no hdf5=yes zfp=no prec=double EXTRA_CXX_FLAGS=-lgfortran HDF5ROOT=/usr/lib/x86_64-linux-gnu/hdf5/openmpi -j2
            make sw4mopt CXX=mpicxx FC=gfortran debug=no hdf5=yes zfp=no prec=double EXTRA_CXX_FLAGS=-lgfortran HDF5ROOT=/usr/lib/x86_64-linux-gnu/hdf5/openmpi -j2
            # make sw4     CXX=mpicxx FC=gfortran debug=no hdf5=yes zfp=no prec=double EXTRA_CXX_FLAGS="-lm -ldl" HDF5ROOT=/usr/lib/x86_64-linux-gnu/hdf5/openmpi -j2
            # make sw4mopt CXX=mpicxx FC=gfortran debug=no hdf5=yes zfp=no prec=double EXTRA_CXX_FLAGS="-lm -ldl" HDF5ROOT=/usr/lib/x86_64-linux-gnu/hdf5/openmpi -j2

      - name: Test SW4
        working-directory: ./pytest
        run: python3 test_sw4.py

      - name: Test SW4mopt
        working-directory: ./pytest-sw4mopt
        run: python3 test_sw4mopt.py


